### ISSUE TITLE
Port to Big Sur and MacForge

### ISSUE THREAD

**Issue by cooljeanius** [npyl/EnhanceDiskUtility#7]
MySIMBL is deprecated and replaced by MacForge, and FireWolf's Repair Permissions Utility hasn't been updated for Big Sur yet

**Comment by cooljeanius** [comment]
@npyl is this repository still maintained?

**Comment by npyl** [comment]
No unfortunately

**Comment by cooljeanius** [comment]
> No unfortunately

aw man... do you know any other similar projects that attempt to do something similar that I could use instead?
